#!/usr/bin/env ruby
require './lib/coord'
require './lib/cell'
require './lib/board'
require './lib/move'

m = Move.new(Board.new(22,143,"board.txt"))
c = 0
while true do
  puts m.board
  puts
  print "Generation: #{c}"
  sleep 0.1
  m.move
  c += 1
end
